=== CallumDarling/devilspie/devilspie.dtd
<!--
This is the DTD for Devil's Pie configuration files
Author: Ross Burton <ross@burtonini.com>
-->

<!--
Root element
-->

<!ELEMENT devilspie (flurb)*>

<!ELEMENT flurb (matchers, actions)>
<!ATTLIST flurb name CDATA #IMPLIED>

<!ELEMENT matchers (matcher)*>
<!ELEMENT actions (action)*>

<!ELEMENT matcher (property)*>
<!ATTLIST matcher name CDATA #REQUIRED>

<!ELEMENT action (property)*>
<!ATTLIST action name CDATA #REQUIRED>

<!ELEMENT property EMPTY>
<!ATTLIST property
	name CDATA #REQUIRED
	value CDATA #REQUIRED
>

=== CallumDarling/devilspie/sample-config.xml
<?xml version="1.0"?>
<!DOCTYPE devilspie SYSTEM "devilspie.dtd">

<!-- The root element is devilspie -->
<devilspie>

  <!--
  This starts a new flurb, which is a set of matchers and actions.
  This flurb matches all windows, and prints out the window name and application name
  -->
  <flurb name="Print Window Names">
    <matchers>
      <!-- this is a matcher which always returns true. The full class name must be used -->
      <matcher name="DevilsPieMatcherAlways"/>
    </matchers>
    <actions>
      <!-- this action prints out the window and application name -->
      <action name="DevilsPieActionDebug"/>
    </actions>
  </flurb>

  <!--
  This flurb is actually useful. Match any XChat window, and pin it so that it
  appears on all workspaces.
  -->
  <flurb name="X-Chat on all Desktops">
    <matchers>
      <matcher name="DevilsPieMatcherWindowName">
        <property name="application_name" value="Xchat"/>
      </matcher>
    </matchers>
    <actions>
      <action name="DevilsPieActionSetWorkspace">
        <property name="pinned" value="TRUE"/>
      </action>
    </actions>
  </flurb>

  <flurb>
    <matchers>
      <matcher name="DevilsPieMatcherWindowName">
        <property name="window_title" value="gnome-panel"/>
      </matcher>
    </matchers>
    <actions>
      <action name="DevilsPieActionLayer">
        <property name="above" value="FALSE"/>
      </action>
    </actions>
  </flurb>

  <!--
  This will put all GNOME Calculators on the second workspace.
  Note that the workspace number is a 1-based index, not a
  0-based index.
  -->
  <flurb>
    <matchers>
      <matcher name="DevilsPieMatcherWindowName">
        <property name="application_name" value="Gnome-calculator"/>
      </matcher>
    </matchers>
    <actions>
      <action name="DevilsPieActionSetWorkspace">
        <property name="workspace_index" value="2"/>
      </action>
      <action name="DevilsPieActionHide">
        <property name="skip_tasklist" value="TRUE"/>
      </action>
    </actions>
  </flurb>


  <!--
   Start Galeon browser without window decorations on 3rd workspace
  -->
  <flurb>
    <matchers>
      <matcher name="DevilsPieMatcherWindowName">
        <property name="application_name" value="Galeon"/>
      </matcher>
    </matchers>
    <actions>
      <action name="DevilsPieActionDecorate">
        <property name="decorated" value="FALSE"/>
      </action>
      <action name="DevilsPieActionSetWorkspace">
        <property name="workspace_index" value="3"/>
      </action>
    </actions>
  </flurb>

  <!--
  Move all GNOME Dictionary windows to 200x200, 100 px wide and 50 px high.
  -->
  <flurb>
    <matchers>
      <matcher name="DevilsPieMatcherWindowName">
        <property name="application_name" value="gnome-dictionary"/>
      </matcher>
    </matchers>
    <actions>
      <action name="DevilsPieActionSetGeometry">
        <property name="xoffset" value="200"/>
        <property name="yoffset" value="200"/>
        <property name="width" value="100"/>
        <property name="height" value="50"/>
      </action>
    </actions>
  </flurb>
</devilspie>
